<?xml version="1.0" encoding="utf-8"?><Database Name="Route2Flow" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=rd.excelink.co.th;Initial Catalog=Route2Flow;Persist Security Info=True;User ID=svsa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Route2FlowConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ActionMessage" Member="ActionMessages">
    <Type Name="ActionMessage">
      <Column Name="wid" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="bid" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="usrid" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="actiondate" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="actiontime" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="actionmsg" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="presentto" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="commandcode" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Signature" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.WType" Member="WTypes">
    <Type Name="WType">
      <Column Name="CODE" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DSC" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Attachment" Member="Attachments">
    <Type Name="Attachment">
      <Column Name="wid" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="bid" Type="System.String" DbType="VarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="attachdate" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="attachtime" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="attachname" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="userattach" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="contextattach" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="itemno" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="actionmsg" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="linkwid" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="allowupdate" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.BusinessUnit" Member="BusinessUnits">
    <Type Name="BusinessUnit">
      <Column Name="BU" Type="System.String" DbType="VarChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(105) NOT NULL" CanBeNull="false" />
      <Column Name="outnumber" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="prefix" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="DID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DSC" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BU" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="WFID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Wfdsc" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="StateCode" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="RegisterNo" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SendNo" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ItemNo" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="DocuName" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="HomeDir" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="CLASS" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(14) NOT NULL" CanBeNull="false" />
      <Association Name="Department_UserLogin" Member="UserLogins" ThisKey="DID" OtherKey="DID" Type="UserLogin" />
    </Type>
  </Table>
  <Table Name="dbo.Member" Member="Members">
    <Type Name="Member">
      <Column Name="RID" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PID" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Process" Member="Processes">
    <Type Name="Process">
      <Column Name="PID" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RID" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="RegisterNo" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleID" Type="System.String" DbType="VarChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="F1" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="F2" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="F3" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="F4" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="F5" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="F6" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="F7" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Route" Member="Routes">
    <Type Name="Route">
      <Column Name="RID" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="LaunchDate" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ExpiryDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Authors" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="WFID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WNO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Docuname" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Step" Member="Steps">
    <Type Name="Step">
      <Column Name="RID" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Step" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Action" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PID" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserLogin" Member="UserLogins">
    <Type Name="UserLogin">
      <Column Name="UID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DepType" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SSN" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Tel1" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Tel2" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="SecCode" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="UserType" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Association Name="Department_UserLogin" Member="Department" ThisKey="DID" OtherKey="DID" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.WLog" Member="WLogs">
    <Type Name="WLog">
      <Column Name="WID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ActionMsg" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LogDate" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="LogTime" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="IP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[Work]" Member="Works">
    <Type Name="Work">
      <Column Name="WID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RID" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="FID" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="WType" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="WSubtype" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="WSubject" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="WOrigin" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="WOwner" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="WDate" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="WDsc" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SecLevCode" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="PriorityCode" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="RegisterDep" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="RegisterUID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="RegisterNo" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="DateRegistered" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TimeRegistered" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="DateCompleted" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TimeCompleted" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Maxtime" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="RefWork" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ExpireDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Association Name="_Work_WorkInProcess" Member="WorkInProcesses" ThisKey="WID" OtherKey="WID" Type="WorkInProcess" />
    </Type>
  </Table>
  <Table Name="dbo.WorkInProcess" Member="WorkInProcesses">
    <Type Name="WorkInProcess">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RID" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="SenderPID" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="PID" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="SenderDep" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="Dep" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="SenderUID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Action" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DateIn" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TimeIn" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="DateModified" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TimeModified" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="RegisterNo" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="_Work_WorkInProcess" Member="Work" ThisKey="WID" OtherKey="WID" Type="Work" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WStatus" Member="WStatus">
    <Type Name="WStatus">
      <Column Name="Code" Type="System.String" DbType="VarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Dsc" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.WSubtype" Member="WSubtypes">
    <Type Name="WSubtype">
      <Column Name="Wtype" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Dsc" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Dep" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="Granted" Type="System.String" DbType="VarChar(140) NOT NULL" CanBeNull="false" />
      <Column Name="SubWtypeNo" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Used_code" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="AliasPosition" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.SOFTFLOW_sp_CreateRouteWork" Method="SOFTFLOW_sp_CreateRouteWork">
    <Parameter Name="wid" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="RID" Parameter="rID" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="PID" Parameter="pID" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="FID" Parameter="fID" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="wsubject" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="worigin" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="wowner" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="wdate" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="wdsc" Type="System.String" DbType="Text" />
    <Parameter Name="seclevcode" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="prioritycode" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="registerdep" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="registeruid" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="registerno" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="dateregistered" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="timeregistered" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="datecompleted" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="timecompleted" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="Maxtime" Parameter="maxtime" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="RefWork" Parameter="refWork" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ExpireDate" Parameter="expireDate" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Location" Parameter="location" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="status" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="ip" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>